#!/bin/sh
feh --bg-fill ~/.config/dwm/wallpaper.jpg &
picom -b & 
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst
xscreensaver -nosplash
volumeicon
/opt/piavin/bin/pia-client %u
dwm
