# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
MAKEOPTS="-j8 -l5"
USE="-gnome X udisks wayland dist-kernel bluetooth opus screencast gstreamer gles2"
FEATURES="${FEATURES} getbinpkg binpkg-request-signature candy "
ACCEPT_LICENSE="*"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://us.mirrors.cicku.me/gentoo/ \
    https://mirror.clarkson.edu/gentoo/ \
    rsync://mirror.clarkson.edu/gentoo/ \
    https://mirrors.kernel.org/gentoo/ \
    https://mirrors.mit.edu/gentoo-distfiles/ \
    rsync://mirrors.mit.edu/gentoo-distfiles/ \
    https://mirror.cs.odu.edu/ \
    https://gentoo.osuosl.org/ \
    https://mirror.planetunix.net/pub/gentoo/ \
    rsync://mirror.planetunix.net/gentoo/ \
    https://mirrors.rit.edu/gentoo/ \
    rsync://mirrors.rit.edu/gentoo/ \
    https://mirror.servaxnet.com/gentoo/ \
    https://mirror.umd.edu/gentoo/"
