require('config.globals')
require('config.lazy')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
    vim.lsp.enable({
      --rust
      "rust-analyzer",
    })
