
[[language]]
name = "python"
language-servers = ["pylsp", "ruff"]
auto-format = true
[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true
[language-server.ruff]
command = "ruff"
args = ["server"]
